Repository tuannguyen2k5/project-group-8, pull requests merged in 2023-02, with the labels that each got.

#18 InformationShippingPage
  views/css/information.css
  views/information.ejs
Labels: enhancement

#25 InformationShippingPage
  views/css/shipping.css
  views/shipping.ejs
Labels: enhancement

#27 Partials
  views/partials/cost-discount.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: enhancement

#28 add payment.css
  views/css/payment.css
  views/payment.ejs
Labels: enhancement

#29 Add routing
  routes/catalog.js
  routes/db.js
  routes/index.js
  routes/site.js
Labels: enhancement

#31 add product page
  views/css/product-detail.css
  views/product-detail.ejs
  views/product.ejs
Labels: enhancement

#37 Add app/controllers
  app/controllers/AccountController.js
  app/controllers/CartController.js
  app/controllers/CatalogController.js
  app/controllers/OrderController.js
  app/controllers/SiteController.js
Labels: enhancement

#42 add momo payment
  services/momo.service.js
Labels: enhancement

#40 add sql scripts
  README.md
  SQL script.sql
Labels: bug, enhancement

#46 fix payment page
  views/payment.ejs
Labels: bug
